# Base
seed: 9999

# FHIR server url
fhir_url: http://localhost:8080/fhir

# Data configs
project: ./hospital_data/
data_name: primary
hospital_data:
    hospital_n: 3
    start_date:
        min: 2025-03-17      # ISO format: YYYY-MM-DD
        max: 2025-09-21      # ISO format: YYYY-MM-DD
    days: 7
    interval_hour: 0.25
    start_hour:
        min: 9
        max: 10
    end_hour:
        min: 18
        max: 19
    department_per_hospital:
        min: 2
        max: 3
    doctor_per_department:
        min: 1
        max: 1
    working_days:                   # The number of days a doctor can work during the given simulation period, with a random number of days assigned to each doctor.
        min: 5
        max: 7
    doctor_capacity_per_hour:
        min: 4
        max: 4
    doctor_has_schedule_prob: 0     # The probability that a doctor has at least one fixed schedule.
    schedule_coverage_ratio:        # If the doctor has a fixed schedule, the proportion of that schedule relative to the total working hours.
        min: 0.4
        max: 0.6
    appointment_coverage_ratio:   # Proportion of appointment time scheduled with patients outside the doctor's fixed schedule.
        min: 0.2
        max: 0.5
    preference:
        type: ['asap', 'doctor', 'date']    # Types of patient preferences.
        probs: [0.6, 0.2, 0.2]           # Types probability distribution.
    symptom:
        type: ['simple', 'with_history']    # Types of patient history.
        probs: [0.9, 0.1]                   # Types probability distribution.
