# Base
seed: 9999

# FHIR server url
fhir_url: http://localhost:8080/fhir

# Data configs
project: ./synthetic_data/
data_name: hospital_easy_small
hospital_data:
    hospital_n: 30
    start_date:
        min: 2025-03-17      # ISO format: YYYY-MM-DD
        max: 2025-09-21      # ISO format: YYYY-MM-DD
    days: 7
    interval_hour: 0.25
    start_hour:
        min: 9
        max: 10
    end_hour:
        min: 18
        max: 19
    department_per_hospital:
        min: 2
        max: 3   
    doctor_per_department:
        min: 1
        max: 1
    doctor_has_schedule_prob: 0.3   # The probability that a doctor has at least one fixed schedule.
    schedule_coverage_ratio:        # If the doctor has a fixed schedule, the proportion of that schedule relative to the total working hours.
        min: 0.01
        max: 0.2
    appointment_coverage_ratio:   # Proportion of appointment time scheduled with patients outside the doctor's fixed schedule.
        max_chunk_size: 1         # Maximum number of consecutive segments per appointment (e.g., max duration = interval_hour * max_chunk_size).
        min: 0.2
        max: 0.5
    preference:
        type: ['asap', 'doctor']    # Types of patient preferences.
        probs: [0.5, 0.5]           # Types probability distribution.
    symptom:
        type: ['simple', 'with_histpry']    # Types of patient history.
        probs: [0.7, 0.3]                   # Types probability distribution.
